== 主要信令流程

=== 开机附着流程
UE刚开机时, 先进行物理下行同步, 搜索测量进行小区选择, 选择到一个合适或者可接纳的小区后, 驻留并进行附着过程. 附着流程图如下: 

[plantuml]
---------------------------------------------------------------------
@startuml
hide footbox
autonumber "<b><font color=red >[00]"

title 开机附着流程
UE -> eNB: **MSG1** Random Access Preamble
eNB -> UE: **MSG2** Random Access Response
UE -> eNB: **MSG3** RRC Connection Request
eNB -> UE: **MSG4** RRC Connection Setup
UE -> eNB: RRC Connection Setup Complete
eNB -> MME: Initial UE message
UE <--> MME: Identity/Authentication/Security
MME -> eNB: Initial Context Setup Request
eNB -> UE: UE Capability Enquiry
UE -> eNB: UE Capability Information
eNB -> MME: UE Capability Info Indication
eNB -> UE: Security Mode Command
UE -> eNB: Security Mode Complete
eNB -> UE: RRC Connection Reconfiguration
UE -> eNB: RRC Connection Reconfiguration Complete
eNB -> MME: Initial context setup response
UE -> eNB: UL Information Transfer
eNB -> MME: UPLINK NAS TRANSPORT

@enduml
---------------------------------------------------------------------
1. 处在RRC_IDLE态的UE进行Attach过程, 首先发起随机接入过程, 即MSG1消息; <<msg_radom_access_preamble, [Random Access Request]>> 
2. eNB检测到MSG1消息后, 向UE发送随机接入响应消息, 即MSG2消息;<<msg_radom_access_response, [Random Access Response]>>  
3. UE收到随机接入响应后, 根据MSG2的TA调整上行发送时机, 向eNB发送RRCConnectionRequest消息;<<msg_rrc_connection_request, [RRC Connection Request]>>   
4. eNB向UE发送RRCConnectionSetup消息, 包含建立SRB1承载信息和无线资源配置信息; <<msg_rrc_connection_setup, [RRC Connection Setup]>>   
5. UE完成SRB1承载和无线资源配置, 向eNB发送RRCConnectionSetupComplete消息, 包含NAS层Attach request信息; <<msg_rrc_connection_setup_complete, [RRC Connection Setup Complete]>>   
6. eNB选择MME, 向MME发送INITIAL UE MESSAGE消息, 包含NAS层Attach request消息; <<msg_initial_ue_message, [InitialUEMessage]>>
7. NAS message
8. MME向eNB发送INITIAL CONTEXT SETUP REQUEST消息, 请求建立默认承载, 包含NAS层Attach Accept, Activate default EPS bearer context request消息; 
9. eNB接收到INITIAL CONTEXT SETUP REQUEST消息, 如果不包含UE能力信息, 则eNB向UE发送UECapabilityEnquiry消息, 查询UE能力; 
10. UE向eNB发送UECapabilityInformation消息, 报告UE能力信息; 
11. eNB向MME发送UE CAPABILITY INFO INDICATION消息, 更新MME的UE能力信息; 
12. eNB根据INITIAL CONTEXT SETUP REQUEST消息中UE支持的安全信息, 向UE发送SecurityModeCommand消息, 进行安全激活; 
13. UE向eNB发送SecurityModeComplete消息, 表示安全激活完成; 
14. eNB根据INITIAL CONTEXT SETUP REQUEST消息中的ERAB建立信息, 向UE发送RRCConnectionReconfiguration消息进行UE资源重配, 包括重配SRB1和无线资源配置, 建立SRB2, DRB(包括默认承载)等; 
15. UE向eNB发送RRCConnectionReconfigurationComplete消息, 表示资源配置完成; 
16. eNB向MME发送INITIAL CONTEXT SETUP RESPONSE响应消息, 表明UE上下文建立完成; 
17. UE向eNB发送ULInformationTransfer消息, 包含NAS层Attach Complete, Activate default EPS bearer context accept消息; 
18. eNB向MME发送上行直传UPLINK NAS TRANSPORT消息, 包含NAS层Attach Complete, Activate default EPS bearer context accept消息. 


=== 随机接入
