== 主要信令流程

=== 开机附着流程
UE刚开机时, 先进行物理下行同步, 搜索测量进行小区选择, 选择到一个合适或者可接纳的小区后, 驻留并进行附着过程. 附着流程图如下: 

[plantuml]
---------------------------------------------------------------------
@startuml
hide footbox
autonumber "<b><font color=red >[00]"

title 开机附着流程
UE -> eNB: **MSG1** Random Access Preamble
eNB -> UE: **MSG2** Random Access Response
UE -> eNB: **MSG3** RRC Connection Request
eNB -> UE: **MSG4** RRC Connection Setup
UE -> eNB: RRC Connection Setup Complete
eNB -> MME: Initial UE message
UE <--> MME: Identity/Authentication/Security
MME -> eNB: Initial Context Setup Request
eNB -> UE: UE Capability Enquiry
UE -> eNB: UE Capability Information
eNB -> MME: UE Capability Info Indication
eNB -> UE: Security Mode Command
UE -> eNB: Security Mode Complete
eNB -> UE: RRC Connection Reconfiguration
UE -> eNB: RRC Connection Reconfiguration Complete
eNB -> MME: Initial context setup response
UE -> eNB: UL Information Transfer
eNB -> MME: UPLINK NAS TRANSPORT

@enduml
---------------------------------------------------------------------
1. 处在RRC_IDLE态的UE进行Attach过程, 首先发起随机接入过程, 即MSG1消息; <<msg_radom_access_preamble, [Random Access Request]>> 
2. eNB检测到MSG1消息后, 向UE发送随机接入响应消息, 即MSG2消息;<<msg_radom_access_response, [Random Access Response]>>  
3. UE收到随机接入响应后, 根据MSG2的TA调整上行发送时机, 向eNB发送RRCConnectionRequest消息;<<msg_rrc_connection_request, [RRC Connection Request]>>   
4. eNB向UE发送RRCConnectionSetup消息, 包含建立SRB1承载信息和无线资源配置信息; <<msg_rrc_connection_setup, [RRC Connection Setup]>>   
5. UE完成SRB1承载和无线资源配置, 向eNB发送RRCConnectionSetupComplete消息, 包含NAS层Attach request信息; <<msg_rrc_connection_setup_complete, [RRC Connection Setup Complete]>>   
6. eNB选择MME, 向MME发送INITIAL UE MESSAGE消息, 包含NAS层Attach request消息; <<msg_initial_ue_message, [InitialUEMessage]>>
7. NAS message
8. MME向eNB发送INITIAL CONTEXT SETUP REQUEST消息, 请求建立默认承载, 包含NAS层Attach Accept, Activate default EPS bearer context request消息;<<msg_initial_context_setup_req, [Inital Contest Setup Request]>> 
9. eNB接收到INITIAL CONTEXT SETUP REQUEST消息, 如果不包含UE能力信息, 则eNB向UE发送UECapabilityEnquiry消息, 查询UE能力; <<msg_ue_capability_enquir, [UE Capability Enquiry]>>
10. UE向eNB发送UECapabilityInformation消息, 报告UE能力信息; <<msg_ue_capability_info, [UE Capability Information]>>
11. eNB向MME发送UE CAPABILITY INFO INDICATION消息, 更新MME的UE能力信息; <<msg_ue_cap_info_ind, [UE Capability Info Indication]>>
12. eNB根据INITIAL CONTEXT SETUP REQUEST消息中UE支持的安全信息, 向UE发送SecurityModeCommand消息, 进行安全激活; <<msg_security_mode_command, [Security Mode Command]>> 
13. UE向eNB发送SecurityModeComplete消息, 表示安全激活完成;<<msg_security_mode_complete, [Security Mode Complete]>>
14. eNB根据INITIAL CONTEXT SETUP REQUEST消息中的ERAB建立信息, 向UE发送RRCConnectionReconfiguration消息进行UE资源重配, 包括重配SRB1和无线资源配置, 建立SRB2, DRB(包括默认承载)等; <<msg_rrc_connection_reconfig, [RRC Connection Reconfiguration]>>
15. UE向eNB发送RRCConnectionReconfigurationComplete消息, 表示资源配置完成; <<msg_rrc_conn_reconfig_compl,[RRC Connection Reconfiguration Complete]>>
16. eNB向MME发送INITIAL CONTEXT SETUP RESPONSE响应消息, 表明UE上下文建立完成; <<msg_inital_context_setup_rsp,[Inital Context Setup Response]>>
17. UE向eNB发送ULInformationTransfer消息, 包含NAS层Attach Complete, Activate default EPS bearer context accept消息; 
18. eNB向MME发送上行直传UPLINK NAS TRANSPORT消息, 包含NAS层Attach Complete, Activate default EPS bearer context accept消息. 


=== 随机接入

=== S1初始化
[plantuml]
---------------------------------------------------------------------
@startuml
hide footbox
autonumber "<b><font color=red >[00]"

title S1 Setup Request
eNB -> MME: S1 Setup Request
MME -> eNB: S1 Setup Response
eNB -> MME: ENB Direct Information Transfer

@enduml
---------------------------------------------------------------------

1. . <<, [S1 Setup Request]>>
2. S1 Setup Response. <<msg_s1_setup_rsp, [S1 Setup Response]>>
3. ENB Direct Information Transfer.<<msg_ENB_direct_info_transfer, [ENB Direct Information Transfer]>> 

=== 测量报告
[plantuml]
---------------------------------------------------------------------
@startuml
hide footbox
autonumber "<b><font color=red >[00]"

title 测量报告
UE -> eNB: Measurement Report
eNB -> UE: RRC Connection Reconfiguration
UE -> eNB: RRC Connection Reconfiguration Complete
UE -> eNB: Measurement Report
eNB -> UE: RRC Connection Reconfiguration
UE -> eNB: RRC Connection Reconfiguration Complete

@enduml
---------------------------------------------------------------------

1. 测量报告
2. RRC重配置, 设置添加测量报告. <<msg_rrc_conn_reconfig_for_meas_add, [RRC Connection Reconfiguration]>>
3. RRC重配置完成.<<msg_rrc_conn_reconfig_compl, [RRC Connection Reconfiguration Complete]>> 
4. 测量报告 <<msg_meas_report, [Measurement Report]>>
5. RRC测量配置, 设置测量报告. <<msg_rrc_conn_reconfig_for_meas_remove, [RRC Connection Reconfiguration]>>
6. RRC重配置完成. 

=== E-RAB承载管理
在CN和eNodeB上为UE建立业务通道。
[plantuml]
---------------------------------------------------------------------
@startuml
hide footbox
autonumber "<b><font color=red >[00]"

title E-RAB承载管理
participant eNB
MME -> eNB: E-RAB Setup Request
eNB -> MME: E-RAB Setup Response

@endumll
---------------------------------------------------------------------
1. <<msg_erab_setup_req, [E-RAB Setup Request]>>
2. <<msg_erab_setup_rsp, [E-RAB Setup Response]>>

=== X2切换
[plantuml]
---------------------------------------------------------------------
@startuml
hide footbox
autonumber "<b><font color=red >[00]"

title X2切换
participant UE

== Handover Preparation ==
s_eNB -> UE: RRC Connection Reconfigration
UE -> s_eNB: RRC Connection Reconfigration Complete
s_eNB -> UE: Measurement Report
rnote over s_eNB: HO decision
s_eNB -> d_eNB: Handover Request
d_eNB -> s_eNB: Handover Request Ack

== Handover  Execution ==
s_eNB -> UE: RRC Connection Reconfigration
UE -> d_eNB: RRC Connection Reconfigration Complete

== Handover  Completion ==
MME -> d_eNB: Path Switch Request
d_eNB -> MME: Path Switch Request Ack
d_eNB -> s_eNB: UE Context Release
rnote over s_eNB: Release Resource

@endumll
---------------------------------------------------------------------


<<<

// vim: set syntax=asciidoc:
