== 网络层信令解析

[[msg_initial_ue_message]]
=== Initial UE Message
初始直传消息. 基站把从UU口收到的NAS消息发往核心网, 初始ATTACH时, 该Nas消息一般包含ATTACH REQ, 请求在核心网创建上下文. 

.InitialUEMessage
----
S1 Application Protocol
  S1AP-PDU: initiatingMessage (0)
    initiatingMessage
      procedureCode: id-initialUEMessage (12)                   <1>
      criticality: ignore (1)
      value
        InitialUEMessage                                        <2>
          protocolIEs: 5 items
            Item 0: id-eNB-UE-S1AP-ID                           <3>
              ProtocolIE-Field
                id: id-eNB-UE-S1AP-ID (8)
                criticality: reject (0)
                value
                  ENB-UE-S1AP-ID: 1                             <4>
            Item 1: id-NAS-PDU                                  <5>
              ProtocolIE-Field
                id: id-NAS-PDU (26)
                criticality: reject (0)
                value
                  NAS-PDU: 177187869d04074102...
                  Non-Access-Stratum (NAS)PDU
            Item 2: id-TAI                                      <6>
              ProtocolIE-Field
                id: id-TAI (67)
                criticality: reject (0)
                value
                  TAI
                    pLMNidentity: 00f110                        <7>
                    Mobile Country Code (MCC): Unknown (1)
                    Mobile Network Code (MNC): Unknown (01)
                    tAC: 3132                                   <8>
            Item 3: id-EUTRAN-CGI                               <9>
              ProtocolIE-Field
                id: id-EUTRAN-CGI (100)
                criticality: ignore (1)
                value
                  EUTRAN-CGI
                    pLMNidentity: 00f110
                    Mobile Country Code (MCC): Unknown (1)
                    Mobile Network Code (MNC): Unknown (01)
                    cell-ID: 00000020                           <10>
            Item 4: id-RRC-Establishment-Cause                  <11>
              ProtocolIE-Field
                id: id-RRC-Establishment-Cause (134)
                criticality: ignore (1)
                value
                  RRC-Establishment-Cause: mo-Signalling (3)    <12>
----

<1> procedureCode
<2> UE初始消息
<3> id-eNB-UE-S1AP-ID
<4> eNB侧的用户标识
<5> id-NAS-PD
<6> id-TAI
<7> PLMN值
<8> TAC值
<9> id-EUTRAN-CGI
<10> 此值为ECI
<11> id-RRC-Establishment-Cause
<12> RRC建立原因值, 移动终端接入. 此值与<<msg_rrc_connection_request, [RRC Connection Request]>>携带的原因值一致


[[msg_initial_context_setup_req]]
=== Initial Context Setup Request
初始上下文建立请求. 由核心网发往基站, 包含Nas消息ATTACH ACCEPT, 指示基站为该UE分配资源建立数据承载. 

.Initial Context Setup Request
------
S1 Application Protocol
 S1AP-PDU: initiatingMessage (0)
  initiatingMessage
   procedureCode: id-InitialContextSetup (9)
   criticality: reject (0)
   value
     InitialContextSetupRequest                                 <1>
       protocolIEs: 6 items
         Item 0: id-MME-UE-S1AP-ID
           MME-UE-S1AP-ID: 33554442                             <2>
         Item 1: id-eNB-UE-S1AP-ID
           ENB-UE-S1AP-ID: 1                                    <3>
         Item 2: id-uEaggregateMaximumBitrate
           UEAggregateMaximumBitrate                            <4>
             uEaggregateMaximumBitRateDL: 20480000              <5>
             uEaggregateMaximumBitRateUL: 4096000               <6>
         Item 3: id-E-RABToBeSetupListCtxtSUReq                 <7>
           E-RABToBeSetupListCtxtSUReq: 1 item
             Item 0: id-E-RABToBeSetupItemCtxtSUReq   
               E-RABToBeSetupItemCtxtSUReq
                 e-RAB-ID: 5                                    <8>
                 e-RABlevelQoSParameters                        <9>
                   qCI: 7                                       <10>
                   allocationRetentionPriority                  <11>
                     priorityLevel: highest (1)                 <12>
                     pre-emptionCapability: may-trigger-pre-emption (1)   <13>
                     pre-emptionVulnerability: pre-emptable (1)           <14>
                   gbrQosInformation                            <15>
                     e-RAB-MaximumBitrateDL: 0
                     e-RAB-MaximumBitrateUL: 0
                     e-RAB-GuaranteedBitrateDL: 0
                     e-RAB-GuaranteedBitrateUL: 0
                 0... .... Extension Present Bit: False
                 transportLayerAddress: 0a5878cc 
                   transportLayerAddress(IPv4): 10.88.120.204   <16>
                 gTP-TEID: 0000048a                             <17>
                 nAS-PDU: 27dac5cd...
                 Non-Access-Stratum (NAS)PDU
                   [message ignore]                             <18>
         Item 4: id-UESecurityCapabilities
           UESecurityCapabilities                               <19>
             ..0. .... Extension Present Bit: False
             encryptionAlgorithms: c000                         <20>
             ...0 .... Extension Present Bit: False
             integrityProtectionAlgorithms: c000                <21>
         Item 5: id-SecurityKey
           SecurityKey: dc1e1e... [bit length 256]              <22>

------

<1> 初始化上下文建立请求
<2> 核心网侧UE用户标识. 在eNodeB保存的UE上下文释放之前, S1接口都是用同样的一对MME-eNodeB S1AP ID来识别UE. 此值与eNB-UE-S1AP-ID不同
<3> 基站侧用户标识
<4> AMBR (Aggregate Maximum Bit Rate)是集合最大比特速率, 在UE开户时设置, 系统通过限制流量方式禁止一组数据流集合的比特速率超过AMBR, 多个EPS承载可以共享一个AMBR. 对于UE AMBR带宽管理是限制一个UE的所有Non-GBR承载的速率之和不会超过UE AMBR. 如果开户时AMBR设置为0, 则初始上下文建立失败, 会回复INITIAL CONTEXT SETUP FAILURE消息且原因值可能为"Semantic Error". (因为协议没有完全对应的原因值, 所以原因值和产品实现有关. )该值定义了用户SIM的最大下载速率, 分为下行和上行. 
<5> 下行AMBR, EPC开户配置
<6> 上行AMBR, EPC开户配置
<7> 需要建立的E-RAB的列表, 初始接入时只包含默认承载的信息. 因此只有一项. 
<8> eNodeB分配的管理E-RAB的标识. 默认承载建立时, E-RAB-ID默认为5. 专用承载为其它值. ERAB-ID的有效范围也同样是5-15;  故我们看到的默认承载建立其ERAB-ID都是从5开始编号的. 
<9> RAB Qos参数等级
<10> 终端开户的CQI. 不同QCI的SDF映射到不同的EPS承载. 默认承载只能是Non-GBR类型
<11> 分配资源的优先级配置(包括优先级和抢占指示器)
<12> 此处为优先级1最高级, 如果配置为"no priority", 则不考虑下面两个参考的配置. 
<13> 配置为＂may-trigger-pre-emption＂, 表示分配可触发抢占过程. 若配置为
"shall-not-trigger-pre-emption"表示分配不可触发抢占过程. 
<14> 表示某ERAB的资源能否被其他ERAB抢占. 此处设置为"pre-emptable", 表示该E-RAB应该包含在抢占过程中. 
<15> //later
<16> UGW分配的GTPU对端地址(传输层地址), 应该等于eNodeB IPPATH中设置的UGW业务地址. 如果地址不相等, 则eNodeB传输资源申请失败, 会回复INITIAL CONTEXT SETUP FAILURE消息且原因值为"Transport Resource Unavailable". 
<17> GTP遂道终结点, 此处指的是上行GTP遂道终结点, 或者说 UGW分配的GTPU对端端口. eNodeB在申请传输资源并分配本端的地址和端口后, 建立GTPU实体. 默认承载和专有承载实际上使用的是不同的GTPU隧道. 
<18> NAS PDU未做解析
<19> UE的安全能力, 在NAS Attach Request中包含了网络能力. 这里主要体现了加密算法和完全性保护算法. 
<20> 加密算法: 比特映射中每一个位置表示一种加密算法: "所有比特为0" - UE 支持EEA0, 不支持其它算法;  "first bit" - 128-EEA1,; "second bit" - 128-EEA2, 其它比特保留以备以后使用. 值 '1'表示支持, 值 '0'表示不支持该算法. 
<21> 完整性算法: 比特映射中每一个位置表示一种完整性保护算法: "all bits equal to 0" – UE只支持 EIA0 ([15]);  "first bit" - 128-EIA1; "second bit" - 128-EIA2. 其它比特保留以备以后使用. 值'1'表示支持, 值 '0'表示不支持该算法
<22> 安全密钥. 核心网和UE之间NAS层的鉴权和安全过程之后, 通过初始密钥生成的KeNodeB, eNodeB收到后会导出AS层的安全密钥. 


[[msg_ue_cap_info_ind]]
=== UE Capability Info Indication
UE能力上报消息, 由基站发往核心网, 将RRC_UE_CAP_INFO中的内容转发到核心网. 这条消息与上一条消息是基站透传的结果, 上一条消息是UE向基站上报无线接入能力, 这条消息是基站把UE的无线接入能力透传给MME. 

.UE Capability Info Indication
------
S1 Application Protocol
 S1AP-PDU: initiatingMessage (0)
  initiatingMessage
   procedureCode: id-UECapabilityInfoIndication (22)
   criticality: ignore (1)
   value
    UECapabilityInfoIndication                                  <1>
     protocolIEs: 3 items
      Item 0: id-MME-UE-S1AP-ID
         MME-UE-S1AP-ID: 33554442                               <2>
      Item 1: id-eNB-UE-S1AP-ID
         ENB-UE-S1AP-ID: 1                                      <3>
      Item 2: id-UERadioCapability
         UERadioCapability: 00da01018c518b82e0bbf06ec4...
          UERadioAccessCapabilityInformation                    <4>          
           criticalExtensions: c1 (0)
            c1: ueRadioAccessCapabilityInformation-r8 (0)
             ueRadioAccessCapabilityInformation-r8
              ue-RadioAccessCapabilityInfo: 4020318...
               UECapabilityInformation
                rrc-TransactionIdentifier: 1
                criticalExtensions: c1 (0)
                 c1: ueCapabilityInformation-r8 (0)
                  ueCapabilityInformation-r8
                   ue-CapabilityRAT-ContainerList: 1 item
                    Item 0
                     UE-CapabilityRAT-Container
                      rat-Type: eutra (0)                      <5>
                      ueCapabilityRAT-Container: c51...
                      UE-EUTRA-Capability                      <6>
                       accessStratumRelease: rel9 (1)          <7>
                       ue-Category: 3                          <8>
                       pdcp-Parameters                         <9>
                        supportedROHC-Profiles                 <10>
                         ...1 .... profile0x0001: True
                         .... 1... profile0x0002: True
                         .... .0.. profile0x0003: False
                         .... ..0. profile0x0004: False
                         .... ...0 profile0x0006: False
                         0... .... profile0x0101: False
                         .0.. .... profile0x0102: False
                         ..0. .... profile0x0103: False
                         ...0 .... profile0x0104: False
                       phyLayerParameters                     <11>
                        .... 0... ue-TxAntennaSelectionSupported: False  <12>
                        .... .0.. ue-SpecificRefSigsSupported: False     <13>
                       rf-Parameters                          <14>
                        supportedBandListEUTRA: 3 items
                         Item 0
                          SupportedBandEUTRA
                           bandEUTRA: 38
                           ..0. .... halfDuplex: False
                         Item 1
                          SupportedBandEUTRA
                           bandEUTRA: 39
                           .0.. .... halfDuplex: False
                         Item 2
                          SupportedBandEUTRA
                           bandEUTRA: 40
                           0... .... halfDuplex: False
                       measParameters
                        bandListEUTRA: 3 items
                         Item 0
                          BandInfoEUTRA
                           interFreqBandList: 3 items
                            Item 0
                             InterFreqBandInfo
                              .... ..1. interFreqNeedForGaps: True
                            Item 1
                             InterFreqBandInfo
                              .... ...1 interFreqNeedForGaps: True
                            Item 2
                             InterFreqBandInfo
                              1... .... interFreqNeedForGaps: True
                         Item 1
                          BandInfoEUTRA
                           interFreqBandList: 3 items
                            Item 0
                             InterFreqBandInfo
                              1... .... interFreqNeedForGaps: True
                            Item 1
                             InterFreqBandInfo
                              .1.. .... interFreqNeedForGaps: True
                            Item 2
                             InterFreqBandInfo
                              ..1. .... interFreqNeedForGaps: True
                         Item 2
                          BandInfoEUTRA
                           interFreqBandList: 3 items
                            Item 0
                             InterFreqBandInfo
                              ..1. .... interFreqNeedForGaps: True
                            Item 1
                             InterFreqBandInfo
                              ...1 .... interFreqNeedForGaps: True
                            Item 2
                             InterFreqBandInfo
                              .... 1... interFreqNeedForGaps: True
                       featureGroupIndicators: 7e0dd880 [bit length 32]
                        0... .... = Indicator 1: Intra-subframe freq hopping for PUSCH scheduled by UL grant; DCI format 3a; PDSCH transmission mode 5; Aperiodic CQI/PMI/RI report on PUSCH: Mode 2-0 and 2-2 - Not supported
                        .1.. .... = Indicator 2: Simultaneous CQI and ACK/NACK on PUCCH (format 2a/2b); Absolute TPC command for PUSCH; Resource alloc type 1 for PDSCH; Periodic CQI/PMI/RI report on PUCCH: Mode 2-0 and 2-1 - Supported
                        ..1. .... = Indicator 3: 5bit RLC UM SN; 7bit PDCP SN - Supported
                        ...1 .... = Indicator 4: Short DRX cycle - Supported
                        .... 1... = Indicator 5: Long DRX cycle; DRX command MAC control element - Supported
                        .... .1.. = Indicator 6: Prioritised bit rate - Supported
                        .... ..1. = Indicator 7: RLC UM - Supported
                        .... ...0 = Indicator 8: EUTRA RRC_CONNECTED to UTRA CELL_DCH PS handover - Not supported
                        0... .... = Indicator 9: EUTRA RRC_CONNECTED to GERAN GSM_Dedicated handover - Not Supported
                        .0.. .... = Indicator 10: EUTRA RRC_CONNECTED to GERAN (Packet_) Idle by Cell Change Order; EUTRA RRC_CONNECTED to GERAN (Packet_) Idle by Cell Change Order with NACC - Not supported
                        ..0. .... = Indicator 11: EUTRA RRC_CONNECTED to CDMA2000 1xRTT CS Active handover - Not supported
                        ...0 .... = Indicator 12: EUTRA RRC_CONNECTED to CDMA2000 HRPD Active handover - Not supported
                        .... 1... = Indicator 13: Inter-frequency handover - Supported
                        .... .1.. = Indicator 14: Measurement reporting event: Event A4 - Neighbour > threshold; Measurement reporting event: Event A5 - Serving < threshold1 & Neighbour > threshold2 - Supported
                        .... ..0. = Indicator 15: Measurement reporting event: Event B1 - Neighbour > threshold - Not supported
                        .... ...1 = Indicator 16: non-ANR related periodical measurement reporting - Supported
                        1... .... = Indicator 17: Periodical measurement reporting for SON / ANR; ANR related intra-frequency measurement reporting events - Supported
                        .1.. .... = Indicator 18: ANR related inter-frequency measurement reporting events - Supported
                        ..0. .... = Indicator 19: ANR related inter-RAT measurement reporting events - Not supported
                        ...1 .... = Indicator 20: SRB1 and SRB2 for DCCH + 8x AM DRB; SRB1 and SRB2 for DCCH + 5x AM DRB + 3x UM DRB (if indicator 7 is supported) - Supported
                        .... 1... = Indicator 21: Predefined intra- and inter-subframe frequency hopping for PUSCH with N_sb > 1; Predefined inter-subframe frequency hopping for PUSCH with N_sb > 1 - Supported
                        .... .0.. = Indicator 22: UTRAN measurements, reporting and measurement reporting event B2 in E-UTRA connected mode - Not supported
                        .... ..0. = Indicator 23: GERAN measurements, reporting and measurement reporting event B2 in E-UTRA connected mode - Not supported
                        .... ...0 = Indicator 24: 1xRTT measurements, reporting and measurement reporting event B2 in E-UTRA connected mode - Not supported
                        1... .... = Indicator 25: Inter-frequency measurements and reporting in E-UTRA connected mode - Supported
                        .0.. .... = Indicator 26: HRPD measurements, reporting and measurement reporting event B2 in E-UTRA connected mode - Not supported
                        ..0. .... = Indicator 27: EUTRA RRC_CONNECTED to UTRA CELL_DCH CS handover - Not supported
                        ...0 .... = Indicator 28: TTI bundling - Not supported
                        .... 0... = Indicator 29: Semi-Persistent Scheduling - Not supported
                        .... .0.. = Indicator 30: Undefined - Not supported
                        .... ..0. = Indicator 31: Undefined - Not supported
                        .... ...0 = Indicator 32: Undefined - Not supported
                       interRAT-Parameters
                       nonCriticalExtension
                        phyLayerParameters-v920
                        interRAT-ParametersGERAN-v920
                        csg-ProximityIndicationParameters-r9
                        neighCellSI-AcquisitionParameters-r9
                        son-Parameters-r9
                        nonCriticalExtension
                         lateNonCriticalExtension: 8000000000

------

<1> UE无线接入能力信息. 共三项. 
<2> 核心网侧UE用户标识. 在eNodeB保存的UE上下文释放之前, S1接口都是用同样的一对MME-eNodeB S1AP ID来识别UE. 
<3> 基站侧的UE用户标识. 
<4> UE无线接入能力信息
<5> 支持EUTRAN
<6> UE capability
<7> rel9
<8> UE Category 3
<9> PDCP 参数
<10> 支持ROHC的能力集, 支持1, 2模式
<11> PHY层参数
<12> later
<13> later
<14> RF参数


[[msg_inital_context_setup_rsp]]
=== Inital Context Setup Response

.Inital Context Setup Response
------
S1 Application Protocol
  S1AP-PDU: successfulOutcome (1)
    successfulOutcome
      procedureCode: id-InitialContextSetup (9)                           <1>
      criticality: reject (0)
      value
        InitialContextSetupResponse
          protocolIEs: 3 items
            Item 0: id-MME-UE-S1AP-ID                                     <2>
              ProtocolIE-Field
                id: id-MME-UE-S1AP-ID (0)
                criticality: ignore (1)
                value
                  MME-UE-S1AP-ID: 33554442
            Item 1: id-eNB-UE-S1AP-ID                                     <3>
              ProtocolIE-Field
                id: id-eNB-UE-S1AP-ID (8)
                criticality: ignore (1)
                value
                  ENB-UE-S1AP-ID: 1
            Item 2: id-E-RABSetupListCtxtSURes                            <4>
              ProtocolIE-Field
                id: id-E-RABSetupListCtxtSURes (51)
                criticality: ignore (1)
                value
                  E-RABSetupListCtxtSURes: 1 item
                    Item 0: id-E-RABSetupItemCtxtSURes
                      ProtocolIE-SingleContainer
                        id: id-E-RABSetupItemCtxtSURes (50)
                        criticality: ignore (1)
                        value
                          E-RABSetupItemCtxtSURes
                            e-RAB-ID: 5                                  <5>
                            .... ...0 Extension Present Bit: False
                            transportLayerAddress: 0a58788c              <6>
                              transportLayerAddress(IPv4): 10.88.120.140 
                            gTP-TEID: 0200000a                           <7>

----

<1> 初始文本建立响应
<2> MME侧用户标识33554442
<3> ENB侧用户标识1
<4> E-RABSetupListCtxt 
<5> e-RAB-ID 5
<6> transportLayerAddress
<7> 此处的GTP-TEID为下行GTP-TEID


