#!/bin/sh

echo  "Converting to PDF..."

bundle exec asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -r asciidoctor-diagram -a pdf-style=KaiGenGothicCN LTE信令流程解析loseblue.adoc

echo  "Claning temp files..."
rm *.png
rm *.cache

echo  "Claning done!"

