#!/bin/sh

echo "Converting to HTML..."
bundle exec asciidoctor -r asciidoctor-pdf-cjk-kai_gen_gothic -r asciidoctor-diagram -a html-style=KaiGenGothicCN a.adoc

echo  "Converting to PDF..."
bundle exec asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -r asciidoctor-diagram -a pdf-style=KaiGenGothicCN a.adoc

echo  "Claning temp files..."
rm *.png
rm *.cache

echo  "Claning done!"

